{
  "uid" : "ce99a53259a725a0",
  "name" : "Invalid login - data table",
  "fullName" : "features/tests/Validation.feature:Invalid login - data table",
  "historyId" : "af6cdccb3c63a220aaa53a1d743dbcf7",
  "time" : {
    "start" : 1606689991100,
    "stop" : 1606690025226,
    "duration" : 34126
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "passed",
    "steps" : [ {
      "name" : "Given I open login page",
      "time" : {
        "start" : 1606689991242,
        "stop" : 1606689994835,
        "duration" : 3593
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Then I see validation message for",
      "time" : {
        "start" : 1606689994836,
        "stop" : 1606690005110,
        "duration" : 10274
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: FAILED SUB-STEP: Then I see \"Incorrect username or password entered\" on the page\nSubstep info: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/model.py\", line 1806, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 30, in step_impl\n    ec.text_to_be_present_in_element(element, text), f'Unable to find text: {text}')\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: Unable to find text: Incorrect username or password entered\n\n\nTraceback (of failed substep):\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/model.py\", line 1806, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 30, in step_impl\n    ec.text_to_be_present_in_element(element, text), f'Unable to find text: {text}')\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n\n",
      "statusTrace" : "  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/model.py\", line 1806, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 35, in step_impl\n    ''')\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/runner.py\", line 422, in execute_steps\n    assert False, message\n",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "b931edd1776d7c9",
        "name" : ".table",
        "source" : "b931edd1776d7c9.csv",
        "type" : "text/csv",
        "size" : 220
      }, {
        "uid" : "f9826346557b9bd4",
        "name" : "bug.png",
        "source" : "f9826346557b9bd4.png",
        "type" : "image/png",
        "size" : 124558
      }, {
        "uid" : "f8a585fc95eb871",
        "name" : "bug.png",
        "source" : "f8a585fc95eb871.png",
        "type" : "image/png",
        "size" : 124558
      } ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 3,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "Given I open login page",
      "time" : {
        "start" : 1606690005148,
        "stop" : 1606690006417,
        "duration" : 1269
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "Then I see validation message for",
      "time" : {
        "start" : 1606690006417,
        "stop" : 1606690025226,
        "duration" : 18809
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "c7a59ea0efe26ab9",
        "name" : ".table",
        "source" : "c7a59ea0efe26ab9.csv",
        "type" : "text/csv",
        "size" : 220
      } ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 4,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "tag",
    "value" : "regression"
  }, {
    "name" : "feature",
    "value" : "Login"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 1,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 2,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "1e426f1bb465a30f",
        "reportUrl" : "https://one-focus.github.io/python-behave-allure-base/11//#testresult/1e426f1bb465a30f",
        "status" : "passed",
        "time" : {
          "start" : 1606689691253,
          "stop" : 1606689697895,
          "duration" : 6642
        }
      }, {
        "uid" : "faf539b10fa7671",
        "reportUrl" : "https://one-focus.github.io/python-behave-allure-base/10//#testresult/faf539b10fa7671",
        "status" : "failed",
        "statusDetails" : "AssertionError: FAILED SUB-STEP: Then I see \"Incorrect username or password entered\" on the page\nSubstep info: Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/model.py\", line 1806, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 30, in step_impl\n    ec.text_to_be_present_in_element(element, text), f'Unable to find text: {text}')\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\nselenium.common.exceptions.TimeoutException: Message: Unable to find text: Incorrect username or password entered\n\n\nTraceback (of failed substep):\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/model.py\", line 1806, in run\n    match.run(runner.context)\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/behave/matchers.py\", line 97, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/basic_steps.py\", line 30, in step_impl\n    ec.text_to_be_present_in_element(element, text), f'Unable to find text: {text}')\n  File \"/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n\n",
        "time" : {
          "start" : 1606689459299,
          "stop" : 1606689473166,
          "duration" : 13867
        }
      } ]
    },
    "tags" : [ "regression" ]
  },
  "source" : "ce99a53259a725a0.json",
  "parameterValues" : [ ]
}